# Generated by Django 4.2.4 on 2023-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='BookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_date',
            field=models.DateField(default=-2000),
            preserve_default=False,
        ),
    ]
